version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./price_tracker.db:/app/price_tracker.db
    restart: unless-stopped
    container_name: price_tracker_web

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./price_tracker.db:/app/price_tracker.db
    restart: unless-stopped
    container_name: price_tracker_worker
    command: python -m app.tasks.scheduler 