[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["/app/**"]

[deploy]
startCommand = "DISABLED"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[nixpacks]
python_version = "3.9.18"
apt-pkgs = ["build-essential", "python3-dev", "gcc", "libc-dev"]